<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Services\**" />
    <Compile Remove="UseCases\**" />
    <EmbeddedResource Remove="Services\**" />
    <EmbeddedResource Remove="UseCases\**" />
    <None Remove="Services\**" />
    <None Remove="UseCases\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ErrorOr" Version="2.1.1" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.2.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.12" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Contracts\Contracts.csproj" />
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

</Project>
