@WebApi.MinimalAPI_HostAddress = http://localhost:5229

GET {{WebApi.MinimalAPI_HostAddress}}/scalar/v1
Accept: application/json

###

GET {{WebApi.MinimalAPI_HostAddress}}/scalar/v1
Accept: application/json

###
